SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[U-47-INDEX ON VIRTUAL COLUMN/REAL COLUMN + FULLTEXT INDEX](c1, c2, c3)
WITH SCHEMABINDING
AS SELECT deptno, loc, dname FROM [dbo].[U-47-DEPT];
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE UNIQUE CLUSTERED INDEX [U-47-different column]
  ON [dbo].[U-47-INDEX ON VIRTUAL COLUMN/REAL COLUMN + FULLTEXT INDEX] ([c1])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [U-47-UI-1]
  ON [dbo].[U-47-INDEX ON VIRTUAL COLUMN/REAL COLUMN + FULLTEXT INDEX] ([c2])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [U-47-UI-2]
  ON [dbo].[U-47-INDEX ON VIRTUAL COLUMN/REAL COLUMN + FULLTEXT INDEX] ([c3], [c2])
  ON [PRIMARY]
GO