SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[U-47-1INDEX / 2INDEX]
WITH SCHEMABINDING
AS SELECT deptno, loc, dname FROM [dbo].[U-47-DEPT];
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE UNIQUE CLUSTERED INDEX [U-47-Clustered index]
  ON [dbo].[U-47-1INDEX / 2INDEX] ([deptno])
  ON [PRIMARY]
GO