SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--------------------------------------

CREATE VIEW [dbo].[U-47-WITH INDEX/WITHOUT INDEX]
WITH SCHEMABINDING
AS SELECT deptno, loc, dname FROM [dbo].[U-47-DEPT];
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE UNIQUE CLUSTERED INDEX [U-47-Index on View]
  ON [dbo].[U-47-WITH INDEX/WITHOUT INDEX] ([deptno])
  ON [PRIMARY]
GO