SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

/* $Header: /ApplicationDB/Stored Procedures/MassJournalNoTableLockSp.sp 1     4/27/06 8:05a pgross $  */
/*
Copyright c Infor Global Solutions, Inc. 2005 - All Rights Reserved

Use, duplication, or disclosure by the Government is subject to restrictions
as set forth in subparagraph (c)(1)(ii) of the Rights in Technical Data and
Computer Software clause at DFARS 252.227-7013, and Rights in Data-General at
FAR 52.227.14, as applicable.

Name of Contractor: MAPICS, Inc., 1000 Windward Concourse Parkway Suite 100,
Alpharetta, GA 30005 USA

Without a license that includes the source code, customer may not, copy,
modify or otherwise update the code contained within this file.  Nor may the
customer merge this code with other computer programs.

With a license that includes the source code, customer may, for its internal
information management and data processing purposes only, copy and modify the
code contained within this file (but not the Limiting Devices) or merge the
code with other computer programs.  The preparation of modified or merged works
will not enlarge the scope of permitted use and any modified or merged version
of the code or any work including any portion of the code shall remain subject
to the provisions of the separately executed license agreement.  All rights and
title to the code remain the sole property of Frontstep, Inc.

Frontstep is a trademark of Frontstep Solutions Group, Inc. All other product
names used in this code are trademarks, registered trademarks, or trade names
of their respective companies.
*/
--  This procedure creates an intent exclusive lock on the journal table,
-- thereby preventing an exclusive table lock from being taken ont he table.
-- This improves concurrency, at the cost of performance for the process that
-- would have taken an exclusive table lock.

/* $Archive: /ApplicationDB/Stored Procedures/MassJournalNoTableLockSp.sp $
 *
 * SL7.04.20 1 93834 pgross Thu Apr 27 08:05:37 2006
 * Purging Journals Causes Serious Blocking
 * Issue #90132, the name of the proc had Mass duplicated for some reason.
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE [dbo].[MassJournalNoTableLockSp]
AS
   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_MassJournalNoTableLockSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_MassJournalNoTableLockSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      EXEC @EXTGEN_SpName
      -- ETP routine must take over all desired functionality of this standard routine:
      RETURN 0
   END
   -- End of Generic External Touch Point code.
DECLARE
  @x int
BEGIN TRAN
SELECT
  @x = 1
FROM journal WITH (UPDLOCK, HOLDLOCK)
WHERE 1=2

--  Poll for the journal posting to be unlocked before rolling back the
-- transaction and exitting.
WHILE 1=1
BEGIN
   WAITFOR DELAY '00:00:05'
   IF EXISTS (SELECT 1
   FROM lasttran WITH (READUNCOMMITTED)
   WHERE lasttran_key = 22
   AND trans_locked = 0)
      BREAK
END

ROLLBACK TRAN
RETURN 0
GO