SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[f_get_version](@id INT)
RETURNS REAL
AS
BEGIN
  RETURN (CAST(SUBSTRING(CONVERT(VARCHAR, SERVERPROPERTY('productversion')), 1, CHARINDEX('.', CONVERT(VARCHAR, SERVERPROPERTY('productversion')))+1) AS REAL))
END;
GO