CREATE TABLE [dbo].[U-84-Columns per primary key 16/1] (
  [st1] [int] NOT NULL,
  [st2] [int] NOT NULL,
  [st3] [int] NOT NULL,
  [st4] [int] NOT NULL,
  [st5] [int] NOT NULL,
  [st6] [int] NOT NULL,
  [st7] [int] NOT NULL,
  [st8] [int] NOT NULL,
  [st9] [int] NOT NULL,
  [st10] [int] NOT NULL,
  [st11] [int] NOT NULL,
  [st12] [int] NOT NULL,
  [st13] [int] NOT NULL,
  [st14] [int] NOT NULL,
  [st15] [int] NOT NULL,
  [st16] [int] NOT NULL,
  [st17] [int] NULL,
  [st18] [int] NULL,
  [st19] [int] NULL,
  [st20] [int] NULL,
  [st21] [int] NULL,
  [st22] [int] NULL,
  [st23] [int] NULL,
  [st24] [int] NULL,
  [st25] [int] NULL,
  [st26] [int] NULL,
  [st27] [int] NULL,
  [st28] [int] NULL,
  [st29] [int] NULL,
  [st30] [int] NULL,
  [st31] [int] NULL,
  [st32] [int] NULL,
  [st33] [int] NULL,
  [st34] [int] NULL,
  [st35] [int] NULL,
  [st36] [int] NULL,
  [st37] [int] NULL,
  [st38] [int] NULL,
  [st39] [int] NULL,
  [st40] [int] NULL,
  [st41] [int] NULL,
  [st42] [int] NULL,
  [st43] [int] NULL,
  [st44] [int] NULL,
  [st45] [int] NULL,
  [st46] [int] NULL,
  [st47] [int] NULL,
  [st48] [int] NULL,
  [st49] [int] NULL,
  [st50] [int] NULL,
  PRIMARY KEY CLUSTERED ([st1], [st2], [st3], [st4], [st5], [st6], [st7], [st8], [st9], [st10], [st11], [st12], [st13], [st14], [st15], [st16])
)
ON [PRIMARY]
GO