CREATE TABLE [ITERATION4].[U-25-CLUSTERED_NONCLUSTERED] (
  [col1] [int] NULL,
  [col2] [int] NULL,
  [col3] [int] NOT NULL,
  CONSTRAINT [U-25-Constr6] PRIMARY KEY CLUSTERED ([col3])
)
ON [PRIMARY]
GO