CREATE TABLE [ITERATION4].[U-37-CLUSTERED/NONCLUSTERED] (
  [col1] [int] NULL,
  [col2] [int] NULL,
  [col3] [int] NULL,
  [col4] [int] NULL,
  [col5] [int] NULL
)
ON [PRIMARY]
GO

CREATE CLUSTERED INDEX [U-37-CLUSTERED/NONCLUSTERED]
  ON [ITERATION4].[U-37-CLUSTERED/NONCLUSTERED] ([col2])
  ON [PRIMARY]
GO