SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ITERATION4].[U-24-2 FK CLAUSE] (
  [col1] [int] NOT NULL,
  [col2] [int] NOT NULL,
  [col3] [int] NOT NULL,
  [col4] AS ([col2]+[col3]) PERSISTED,
  [col5] [int] NOT NULL,
  PRIMARY KEY CLUSTERED ([col1])
)
ON [PRIMARY]
GO

ALTER TABLE [ITERATION4].[U-24-2 FK CLAUSE]
  ADD FOREIGN KEY ([col3]) REFERENCES [ITERATION4].[U-24-1PRIMARY] ([col1])
GO

ALTER TABLE [ITERATION4].[U-24-2 FK CLAUSE]
  ADD FOREIGN KEY ([col1], [col4]) REFERENCES [ITERATION4].[U-24-2PRIMARY] ([col1], [col2])
GO