CREATE TABLE [ITERATION4].[U-18-REFERENCES ON ITSELF] (
  [col1] [int] NOT NULL,
  [col2] [int] NOT NULL,
  [col3] [int] NOT NULL,
  [col4] [int] NOT NULL,
  [col5] [int] NOT NULL,
  PRIMARY KEY CLUSTERED ([col1], [col2]),
  UNIQUE ([col2])
)
ON [PRIMARY]
GO

ALTER TABLE [ITERATION4].[U-18-REFERENCES ON ITSELF]
  ADD FOREIGN KEY ([col3]) REFERENCES [ITERATION4].[U-18-REFERENCES ON ITSELF] ([col2])
GO

ALTER TABLE [ITERATION4].[U-18-REFERENCES ON ITSELF]
  ADD FOREIGN KEY ([col1], [col2]) REFERENCES [ITERATION4].[U-18-REFERENCES ON ITSELF] ([col1], [col2])
GO