CREATE TABLE [ITERATION4].[U-18-FK ON DIFFERENT DATATYPE SIZE] (
  [col1] [int] NOT NULL,
  [col2] [char](11) NULL,
  [col3] [int] NULL,
  [col4] [int] NULL,
  [col5] [int] NULL,
  PRIMARY KEY CLUSTERED ([col1])
)
ON [PRIMARY]
GO

ALTER TABLE [ITERATION4].[U-18-FK ON DIFFERENT DATATYPE SIZE]
  ADD FOREIGN KEY ([col2]) REFERENCES [ITERATION4].[U-18-DIFFERENT DATATYPE SIZE] ([col1])
GO