CREATE TABLE [ITERATION4].[U-7-DIFFERENT_PARTITION_FUNCTION] (
  [col1] [int] NOT NULL,
  [col2] [int] NULL,
  [col3] [int] NULL,
  PRIMARY KEY CLUSTERED ([col1]) ON [U-7-ON_DIFFERENT_PARTITION_FUNCTION] ([col1])
)
ON [U-7-ON_DIFFERENT_PARTITION_FUNCTION] ([col1])
GO