CREATE TABLE [ITERATION4].[U-36-DIFFERENT COL NAMES AND OPERATIONS] (
  [col1] [int] NOT NULL,
  [col2] [int] NULL,
  [col3] [int] NULL,
  [col4] [int] NULL,
  [col5] [int] NULL,
  PRIMARY KEY CLUSTERED ([col1])
)
ON [PRIMARY]
GO

CREATE INDEX [U-36-DIFFERENT COL NAMES AND OPERATIONS]
  ON [ITERATION4].[U-36-DIFFERENT COL NAMES AND OPERATIONS] ([col2], [col3])
  WHERE ([col2]>=(2) AND [col3]<=(4))
  ON [PRIMARY]
GO